### ISSUE TITLE
status is sometimes an URL instead of just a status name

### ISSUE THREAD

**Issue by maelle** [ropensci-org/makeregistry#38]
probably a regex problem in codemetar

**Comment by maelle** [comment]
ah no it is what we expect from codemetar, but maybe here we could remove the repostatus.org URL.

**Comment by maelle** [comment]
actually, maybe we should set an URL to all, since that provides more context, what do you think?

I.e. editing

https://github.com/ropenscilabs/makeregistry/blob/6f9a70fb4850648b6ba4a619a99589e2a8393ef0/R/registry.R#L62-L63

to

```r
  status <- gsub("http(s)?\\:\\/\\/www\\.repostatus\\.org\\/\\#",
                 "https://www.repostatus.org", status)
``` 

(to make URLs all use https)

and

https://github.com/ropenscilabs/makeregistry/blob/6f9a70fb4850648b6ba4a619a99589e2a8393ef0/R/registry.R#L69-L72

to

```r
  if(grepl("ropenscilabs", entry$codeRepository)){
    "https://www.repostatus.org/#concept"
  }else{
    "https://www.repostatus.org/#active"
```

**Comment by sckott** [comment]
Agree to make all of them URLs
