### ISSUE TITLE
New field request

### ISSUE THREAD

**Issue by maelle** [ropensci-org/makeregistry#43]
I'd need a field for the website that'd be "type" for instance. 

* active if it needs to be listed in the active tab (probably all ropensci packages except if their status is different? but why have it in ropensci if it is not active?)
* experimental for ropenscilabs packages, also ropensci-org?
* archived for packages that are in ropensci-archive.

**Comment by maelle** [comment]
At the moment I have 

![image](https://user-images.githubusercontent.com/8360597/92881709-84ec8000-f40f-11ea-8230-338f6b1ba64b.png)


That I made using the GitHub URLs but
* we might need more flexibility one day, and it's easier to tweak a field here than in the Hugo templates.
* for now archived is empty.

**Comment by sckott** [comment]
so a new field `type` with one of three strings: `active`, `experimental`, or `archived`. correct? what if we don't know which of those 3? `null` ?

**Comment by maelle** [comment]
Yes.
I think we'd know based on the GH org (what I assume at the moment: experimental if ropenscilabs, archived if ropensci-achive, active otherwise)?

**Comment by sckott** [comment]
okay.
