### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by maelle** [ropensci-org/makeregistry#45]
@sckott where to add the two lines below for ensuring your GitHub Actions workflows use them?

https://github.com/ropensci-org/makeregistry/blob/3ed6dbddd0dfbbf9233cf5e3f10417440acc18b2/.github/workflows/R-CMD-check.yaml#L72-L73

**Comment by maelle** [comment]
(I imagine the answer is one of the scripts, but I don't know which one :-) )

**Comment by sckott** [comment]
in an `env` key like https://github.com/ropensci-org/makeregistry/blob/master/.github/workflows/build-registry.yml#L10
