### ISSUE TITLE
build registry speed up

### ISSUE THREAD

**Issue by sckott** [ropensci-org/makeregistry#49]
any idea how to cache these packages at this step? https://github.com/ropensci-org/makeregistry/blob/master/.github/workflows/build-registry.yml#L49  @maelle  or @jeroen ?

we have a cache packages step https://github.com/ropensci-org/makeregistry/blob/master/.github/workflows/build-registry.yml#L39 but it doesn't cache the packages in that step at line 49 

the step at line 49 takes about 13-15 min - so it's a significant amount of time of the total time to build registry (~ 30 min)

**Comment by maelle** [comment]
what is cached? What's in DESCRIPTION but not `remotes::install_cran(c("gert", "dplyr", "desc"))`?

**Comment by sckott** [comment]
I'm quite sure the makeregistry dependencies are installed in an above step from there. This step with gert/dplyr/desc just has a lot of dependencies. I just don't understand how to use caching in gh actions

**Comment by maelle** [comment]
I think any packages not in DESCRIPTION is _not_ cached

https://github.com/ropensci-org/makeregistry/blob/f6b94a99ff16b26637a1d343af54cd8bed7a50b5/.github/workflows/R-CMD-check.yaml#L44

So we need to either

* add all dependencies to DESCRIPTION
* change the line to something including the name of the other packages to be cached (which sounds more complicated?).

**Comment by maelle** [comment]
ah no our big problem is that cache doesn't work for scheduled runs " Event Validation Error: The event type schedule is not supported. Only push, pull_request events are supported at this time.".

**Comment by maelle** [comment]
not sure what the workaround would be. maybe waiting until the cache actions supports _all_ events (it supports more than in this warning, it supports all events that have a ref).

**Comment by maelle** [comment]
mmmh so actually scheduled events _have_ a GITHUB_REF. 

@sckott we should replace "actions/cache@v1" with "actions/cache@v2"

**Comment by sckott** [comment]
you made the v1 to v2 change already. correct?

**Comment by jeroen** [comment]
With the new docker-based image, the packages from rspm are used, and it takes only 2 minutes. I don't think it's needed to do caching.

**Comment by sckott** [comment]
thanks, sounds good
