### ISSUE TITLE
can't install waldo

### ISSUE THREAD

**Issue by sckott** [ropensci-org/makeregistry#53]
build registry on gh actions is failing in last 4 days https://github.com/ropensci-org/makeregistry/runs/1906917239?check_suite_focus=true#step:6:223 looks like waldo was also updated 4 days ago on cran - not sure when it will start working. not clear why waldo is failing either

**Comment by sckott** [comment]
@maelle

**Comment by maelle** [comment]
I'm hoping it'll resolve from itself for the R CMD Check workflow.
For the build registry workflow, I am not sure why I had been installing dev dependencies, I changed that.
Thanks for catching this problem, I'll start watching the repo now (uncool oversight on my part!).

**Comment by maelle** [comment]
Ah no I was watching it, I'll just need to pay more attention? :thinking:

**Comment by sckott** [comment]
anyway, looks like its working now
