### ISSUE TITLE
keywords problem

### ISSUE THREAD

**Issue by sckott** [ropensci-org/makeregistry#6]
this is still happening. here's the lastest push https://github.com/ropensci/roregistry/commit/3eba9dbaf1eadc35d4f676cd9da284bda3cdc65b 

my obsevation is that `keywords`and `readme` fields get removed from `raw_cm.json` and `keywords` removed from `registry.json` in one iteration, then get replaced in the next, and then removed, and then put back. 

I'm guessing `keywords` has something to do with `readme` being removed?

the other observation is that it doesn't happen with all packages, only with some - very weird

is there something in the makeregistry code that would cause this behavior?

the GITHUB_PAT is on the server, and it's only used for this, so rate limit shouldn't be an issue. 

@maelle

**Comment by sckott** [comment]
reasonable ideas. will have time later to dig in and think about it

**Comment by maelle** [comment]
Can you install the `gh-message` branch of `codemetar`? It should message the error messages which would help me understand the issue.

```r
remotes::install_github("ropensci/codemetar", ref = "gh-message")
```

**Comment by sckott** [comment]
sure thing. install it on the server you mean?

**Comment by maelle** [comment]
Yes. I hope it will work 🙂

**Comment by sckott** [comment]
i never installed that branch on the server. it all seems to work now though. so close maybe?

**Comment by maelle** [comment]
did this problem happen again?

**Comment by sckott** [comment]
it did happen one more time at least, i can't remember which day/commit, so still a problem, but I don't know why

**Comment by maelle** [comment]
It's definitely a GitHub API problem.

I'll make a PR aiming at ensuring we at least keep the old keywords when we haven't been able to get the current ones from GitHub.

**Comment by maelle** [comment]
should we close this?

**Comment by sckott** [comment]
yeah
